

- name: Create Repository
  docker_container:
    name: cti-stix-store-repository
    image: "mongo:3.4.1"
    state: started
    recreate: yes
    pull: true
    volumes:
    - ./data/db:/data/db
    exposed_ports: 
    - "27018"
    published_ports:
    - "27018:27017"
  when: "run_action != ''" 