---


- name: "Create {{ container_name }}"
  docker_image:
    name: "{{ container_name }}"

    state: present
    path: "{{ path }}"
  when: "build_action == 'local'"

- name: "Pull {{ container_name }}"
  docker_image:
    name: "{{ image_name }}"

    state: present
    pull: yes
  when: "build_action == 'pull'"     

- name: Create Ingest
  docker_container:
    name: unfetter-ctf-ingest
    image: "unfetter/unfetter-ctf-ingest:0.3.6"
    state: started
    volumes:
     - ./config/examples:/tmp/examples
    env:
      - API_PROTOCOL=https
      - API_HOST=apihost
      - API_PORT=3000
      - API_CONTEXT=/
      - MONGO_REPOSITORY=repository
      - MONGO_PORT=27017
      - MONGO_DBNAME=stix
    entrypoint:
     - npm
     - start    
    links:
     - cti-stix-store-repository:repository
     - unfetter-discover-api:apihost
  when: "run_action == 'devrun'"

