
- name: "Create {{ container_name }}"
  docker_image:
    name: "{{ image_name }}"
    state: present
    path: "{{ path }}"
  when: "build_action == 'local'"

- name: "Pull {{ container_name }}"
  docker_image:
    name: "{{ image_name }}"
    state: present
    pull: yes
  when: "build_action == 'pull'"


- name: Create API
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    recreate: yes
    links:
     - cti-stix-store-repository:repository
     - unfetter-pattern-handler:unfetter-pattern-handler
    volumes:
    - ./certs/:/etc/pki/tls/certs     
    env:
      CTF_PARSE_HOST: http://unfetter-ctf-ingest
      STIX_API_PROTOCOL: http
      STIX_API_HOST: cti-stix-store
      STIX_API_PORT: 3000
      STIX_API_PATH: cti-stix-store-api
      MONGO_REPOSITORY: repository
      MONGO_PORT: 27017
      MONGO_DBNAME: stix
      ENV: dev
    # Options: UAC, TEST, DEMO
      RUN_MODE: DEMO
    # If deployed in a proxy, add the proxy's URL here
      HTTPS_PROXY_URL: ""
      PATTERN_HANDLER_DOMAIN: unfetter-pattern-handler
      PATTERN_HANDLER_PORT: 5000
    entrypoint:
    - npm
    - start
  when: "run_action != ''"     