
- name: "Create {{ container_name }}"
  docker_image:
    name: "{{ image_name }}"
    state: present
    path: "{{ path }}"
  when: "build_action == 'local'"

- name: "Pull {{ container_name }}"
  docker_image:
    name: "{{ image_name }}"
    state: present
    pull: yes
  when: "build_action == 'pull'"


- name: Create API
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    links:
     - cti-stix-store-repository:repository
     - unfetter-pattern-handler:unfetter-pattern-handler
    volumes:
    - "{{ prepath }}/unfetter/certs/:/etc/pki/tls/certs"

    # If we are in dev, and thus we are linking in code
    - "{{ prepath+'/unfetter-store/unfetter-discover-api/test:/usr/share/unfetter-discover-api/test' if run_mode=='dev' else '' }}"
    - "{{ prepath+'/unfetter-store/unfetter-discover-api/api:/usr/share/unfetter-discover-api/api' if run_mode=='dev' else '' }}"
    - "{{ prepath+'/unfetter-store/unfetter-discover-api/app.js:/usr/share/unfetter-discover-api/app.js' if run_mode=='dev' else '' }}"

    # If we are in UAC, and thus need the private-config.json
    - "{{ prepath+'/unfetter-store/unfetter-discover-api/config/private-config.json:/usr/share/unfetter-discover-api/config/private-config.json' if use_uac else '' }}"
    
    exposed_ports:
    - "{{ '5555' if run_mode == 'dev' }}"
    published_ports:
     - "{{ '5555:5555' if run_mode == 'dev' }}"
    env:
      CTF_PARSE_HOST: http://unfetter-ctf-ingest
      STIX_API_PROTOCOL: http
      STIX_API_HOST: cti-stix-store
      STIX_API_PORT: 3000
      STIX_API_PATH: cti-stix-store-api
      MONGO_REPOSITORY: repository
      MONGO_PORT: 27017
      MONGO_DBNAME: stix
      ENV: dev
    # Options: UAC, TEST, DEMO
      RUN_MODE: "{{ 'UAC' if use_uac else 'DEMO' }}"
    # If deployed in a proxy, add the proxy's URL here
      HTTPS_PROXY_URL: ""
      PATTERN_HANDLER_DOMAIN: unfetter-pattern-handler
      PATTERN_HANDLER_PORT: 5000
      SOCKET_SERVER_DOMAIN: "{{ 'socketserver' if use_uac}}"
      SOCKET_SERVER_PORT: "{{ '3333' if use_uac}}"
      MONGO_DEBUG: "{{ 'false' if use_uac}}"
    entrypoint:
    - npm 
    - run 
    - "{{ 'start' if run_mode != 'dev' else 'debugdev' }}" 
  when: run_action     